In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
path = r"C:\Users\SHREE\Downloads\Day - 29 - DAX - Tech_Products_Sales_Data.xlsx"
df = pd.read_excel(path)
df

,Transaction ID,Product,Quantity,Unit Price (INR),Date,Customer Name,State,Country,Sales Channel,Payment Type,Sales
0,TX0001,Smartwatch,9,8941,2024-04-12,Vivaan Sastry,Arunachal Pradesh,India,Store,Credit Card,80469
1,TX0002,Desktop PC,9,19827,2024-02-06,Ishaan Madan,Odisha,India,Store,Credit Card,178443
2,TX0003,Desktop PC,4,16640,2023-12-16,Azad Sandhu,Bihar,India,Online,Credit Card,66560
3,TX0004,E-Reader,3,2945,2024-09-11,Shray Chawla,Manipur,India,Online,Credit Card,8835
4,TX0005,Laptop,4,2848,2023-10-24,Zara Kata,Madhya Pradesh,India,Direct,Net Banking,11392
...,...,...,...,...,...,...,...,...,...,...,...
995,TX0996,Desktop PC,3,16668,2024-03-02,Trisha Doctor,Karnataka,India,Store,Cash,50004
996,TX0997,Printer,9,7752,2024-08-20,Kartik Gola,Telangana,India,Store,Debit Card,69768
997,TX0998,Camera,8,6466,2024-06-23,Rhea Thaker,Jharkhand,India,Online,UPI,51728
998,TX0999,Tablet,4,6409,2023-11-27,Tejas Dhar,Odisha,India,Store,Credit Card,25636
999,TX1000,Tablet,8,2524,2023-12-04,Shaan Char,Odisha,India,Store,Net Banking,20192

In [3]:
df.head()

,Transaction ID,Product,Quantity,Unit Price (INR),Date,Customer Name,State,Country,Sales Channel,Payment Type,Sales
0,TX0001,Smartwatch,9,8941,2024-04-12,Vivaan Sastry,Arunachal Pradesh,India,Store,Credit Card,80469
1,TX0002,Desktop PC,9,19827,2024-02-06,Ishaan Madan,Odisha,India,Store,Credit Card,178443
2,TX0003,Desktop PC,4,16640,2023-12-16,Azad Sandhu,Bihar,India,Online,Credit Card,66560
3,TX0004,E-Reader,3,2945,2024-09-11,Shray Chawla,Manipur,India,Online,Credit Card,8835
4,TX0005,Laptop,4,2848,2023-10-24,Zara Kata,Madhya Pradesh,India,Direct,Net Banking,11392

In [4]:
df.tail()

,Transaction ID,Product,Quantity,Unit Price (INR),Date,Customer Name,State,Country,Sales Channel,Payment Type,Sales
995,TX0996,Desktop PC,3,16668,2024-03-02,Trisha Doctor,Karnataka,India,Store,Cash,50004
996,TX0997,Printer,9,7752,2024-08-20,Kartik Gola,Telangana,India,Store,Debit Card,69768
997,TX0998,Camera,8,6466,2024-06-23,Rhea Thaker,Jharkhand,India,Online,UPI,51728
998,TX0999,Tablet,4,6409,2023-11-27,Tejas Dhar,Odisha,India,Store,Credit Card,25636
999,TX1000,Tablet,8,2524,2023-12-04,Shaan Char,Odisha,India,Store,Net Banking,20192

Structure Check

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    1000 non-null   object
 1   Product           1000 non-null   object
 2   Quantity          1000 non-null   int64
 3   Unit Price (INR)  1000 non-null   int64
 4   Date              1000 non-null   object
 5   Customer Name     1000 non-null   object
 6   State             1000 non-null   object
 7   Country           1000 non-null   object
 8   Sales Channel     1000 non-null   object
 9   Payment Type      1000 non-null   object
 10  Sales             1000 non-null   int64
dtypes: int64(3), object(8)
memory usage: 86.1+ KB

Check Missing Values

In [7]:
df.isnull().sum()

Transaction ID      0
Product             0
Quantity            0
Unit Price (INR)    0
Date                0
Customer Name       0
State               0
Country             0
Sales Channel       0
Payment Type        0
Sales               0
dtype: int64

Check Duplicate Records

In [8]:
df.duplicated().sum()

np.int64(0)

Check Duplicate Records (Convert Date)

In [9]:
df["Date"] = pd.to_datetime(df["Date"])
df.dtypes

Transaction ID              object
Product                     object
Quantity                     int64
Unit Price (INR)             int64
Date                datetime64[ns]
Customer Name               object
State                       object
Country                     object
Sales Channel               object
Payment Type                object
Sales                        int64
dtype: object

Validate Sales Calculation

In [11]:
df["Calculated Sales"] = df["Quantity"] * df["Unit Price (INR)"]

(df["Sales"] == df["Calculated Sales"]).all()

np.True_

Basic Statistics

In [12]:
df.describe()

,Quantity,Unit Price (INR),Date,Sales,Calculated Sales
count,1000.000000,1000.000000,1000,1000.00000,1000.00000
mean,4.899000,10509.633000,2024-03-28 07:32:09.600000256,51202.11700,51202.11700
min,1.000000,2040.000000,2023-09-24 00:00:00,2043.00000,2043.00000
25%,3.000000,5962.000000,2023-12-27 18:00:00,20152.50000,20152.50000
50%,5.000000,10208.000000,2024-03-26 00:00:00,39636.50000,39636.50000
75%,7.000000,14846.000000,2024-06-29 00:00:00,74091.00000,74091.00000
max,9.000000,19994.000000,2024-09-23 00:00:00,178443.00000,178443.00000
std,2.540719,5241.520851,NaN,38852.61529,38852.61529

Save File

In [14]:
new_df=df

In [16]:
new_df.to_excel("Tech_Products_Sales_Data_cleaned.xlsx", index=False)

The dataset was inspected, validated, and cleaned successfully.  
No missing or duplicate values were found.  
Date formatting and sales validation ensure the dataset is analysis-ready.